var dailies = {
  "field-boss": {
    task: "Field Boss",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "field-boss",
  },
  "pray-daily": {
    task: "Pray Daily",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "repeatable_quest",
  },
  "chaos-gate": {
    task: "Chaos Gate",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "chaos-gate",
  },
  rapport: {
    task: "Rapport",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "rapport",
  },
  "buzzling-island": {
    task: "Buzzling Island",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "buzzling-island",
  },
  "moko-isle": {
    task: "Moko Isle",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "moko-isle",
  },
  "adventure-island": {
    task: "Adventure Island",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "adventure-island",
  },
  "ocean-co-op": {
    task: "Ocean Co-Op",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "ocean-co-op",
  },
  "trade-skills": {
    task: "Trade Skills",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "trade-skills",
  },
};
