var dailies = {
  "field-boss": {
    task: "Field Boss",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "field-boss",
  },
  "chaos-gate": {
    task: "Chaos Gate",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "chaos-gate",
  },
  rapport: {
    task: "Rapport",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "rapport",
  },
  "indigo-island": {
    task: "Indigo Island",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "indigo-island",
  },
  "Witch's House": {
    task: "Witch's House",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "witchs-house",
  },
  "trial-of-honor": {
    task: "Trial of Honor",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "trial-of-honor",
  },
  "adventure-island": {
    task: "Adventure Island",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "adventure-island",
  },
  "ocean-co-op": {
    task: "Ocean Co-Op",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "ocean-co-op",
  },
  "trade-skills": {
    task: "Trade Skills",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "trade-skills",
  },
};
