var dailies = {
  "field-boss": {
    task: "Field Boss",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "field-boss",
  },
  "chaos-gate": {
    task: "Chaos Gate",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "chaos-gate",
  },
  // rapport: {
  //   task: "Rapport",
  //   url: "#",
  //   short: true,
  //   desc: "Placeholder",
  //   img: "rapport",
  // },
  "trade-skills": {
    task: "Trade Skills",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "trade-skills",
  },
  "adventure-island": {
    task: "Adventure Island",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "adventure-island",
  },
  "dancing-maharaka": {
    task: "Dancing Maharaka",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "dancing-maharaka",
  },
  "buzzling-island": {
    task: "Buzzling Island",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "buzzling-island",
  },
  "ocean-co-op": {
    task: "Ocean Co-Op",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "ocean-co-op",
  },
};
