var weeklychar = {
  "bloodstone-shop": {
    task: "Bloodstone Shop",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "sylmael-bloodstone",
  },
  "astrogem-vendor": {
    task: "Astrogem Vendor",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "uncommon_astrogem_chest",
  },
  "solo-mode-exchange": {
    task: "Solo Mode Exchange",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "solo-mode-exchange",
  },
  "cathedral-abyssal-dungeon": {
    task: "Cathedral Dungeon",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "endgame-content",
  },
  "serca-shadow-raid": {
    task: "Serca Raid",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "endgame-content",
  },
  "kazeros-kazeros-raid": {
    task: "Kazeros Raid",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "endgame-content",
  },
  "armoche-kazeros-raid": {
    task: "Armoche Raid",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "endgame-content",
  },
  "extra-rewards": {
    task: "Extra Rewards",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "extra-rewards",
  },
  "haal's-hourglass": {
    task: "Haal's Hourglass",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "haals-hourglass",
  },
  paradise: {
    task: "Paradise",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "paradise",
  },
};
