var weeklychar = {
  "solo-mode-exchange": {
    task: "Solo Mode Exchange",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "solo-mode-exchange",
  },
  "bloodstone-shop": {
    task: "Bloodstone Shop",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "sylmael-bloodstone",
  },
  "weekly-una-task-1": {
    task: "Weekly Una Task 1",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "weekly-una",
  },
  "weekly-una-task-2": {
    task: "Weekly Una Task 2",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "weekly-una",
  },
  "weekly-una-task-3": {
    task: "Weekly Una Task 3",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "weekly-una",
  },
  "kazeros-kazeros-raid": {
    task: "Kazeros Raid",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "endgame-content",
  },
  "armoche-kazeros-raid": {
    task: "Armoche Raid",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "endgame-content",
  },
  "mordum-kazeros-raid": {
    task: "Mordum Raid",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "endgame-content",
  },
  "brelshaza-kazeros-raid": {
    task: "Brelshaza Raid",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "endgame-content",
  },
  "aegir-kazeros-raid": {
    task: "Aegir Raid",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "endgame-content",
  },
  "echidna-kazeros-raid": {
    task: "Echidna Raid",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "endgame-content",
  },
  "behemoth-epic-raid": {
    task: "Behemoth Raid",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "endgame-content",
  },
  "extra-rewards": {
    task: "Extra Rewards",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "extra-rewards",
  },
  Paradise: {
    task: "Paradise",
    url: "#",
    short: true,
    desc: "Placeholder",
    img: "paradise",
  },
};
